### ISSUE TITLE
Add `is_file`

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell_archive#1]
```
Traceback (most recent call last):
  File "/home/gram/Documents/dephell/dephell/cli.py", line 115, in main
    result = task()
  File "/home/gram/Documents/dephell/dephell/commands/deps_convert.py", line 88, in __call__
    'project': resolver.graph.metainfo,
  File "/home/gram/Documents/dephell/dephell/controllers/_graph.py", line 239, in metainfo
    return RootDependency.get_metainfo(*self._roots)
  File "/home/gram/Documents/dephell/dephell/models/root.py", line 147, in get_metainfo
    info = root.package.metainfo
  File "/home/gram/Documents/dephell_discover/dephell_discover/_cached_propery.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/gram/Documents/dephell_discover/dephell_discover/_root.py", line 84, in metainfo
    return MetaInfo.parse(paths=paths)
  File "/home/gram/Documents/dephell_discover/dephell_discover/_metainfo.py", line 45, in parse
    if path.is_file():
  File "/usr/local/lib/python3.7/dist-packages/dephell_archive/_path.py", line 177, in __getattr__
    return getattr(self.member_path, name)
AttributeError: 'PurePosixPath' object has no attribute 'is_file'

```

**Comment by orsinium** [comment]
Closed in #2
